networks:
  app-network:
    driver: bridge

volumes:
  user_db_data:
  restaurant_db_data:
  order_db_data:
  minio-data:
  redis_users_data:
  redis_restaurants_data:
  redis_orders_data:
  node_modules_frontend:

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - food-delivery-platform-frontend
      - food-delivery-platform-user
      - food-delivery-platform-restaurant
      - food-delivery-platform-order
      - minio
    networks:
      - app-network

  food-delivery-platform-frontend:
    build:
      context: ./delivery-ui
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - '5173'
    volumes:
      - ./delivery-ui:/app
      - node_modules_frontend:/app/node_modules
      - /app/node_modules/.vite
    environment:
      - NODE_ENV=development
      - VITE_USER_API_URL=${VITE_USER_API_URL}
      - VITE_RESTAURANT_API_URL=${VITE_RESTAURANT_API_URL}
      - VITE_ORDER_API_URL=${VITE_ORDER_API_URL}
      - VITE_MINIO_URL=${VITE_MINIO_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=24678
    networks:
      - app-network
    stdin_open: true
    tty: true

  food-delivery-platform-user:
    build:
      context: ./foodDeliveryPlatformUser
      dockerfile: Dockerfile
    container_name: user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://userDB:5432/${USER_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://userDB:5432/${USER_DB}
      - SPRING_LIQUIBASE_USER=${POSTGRES_USERNAME}
      - SPRING_LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ALLOWED_ORIGINS=http://localhost,http://localhost:5173,http://frontend:5173
      - ALLOWED_HEADERS=*
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
    expose:
      - '8080'
    ports:
      - "8081:8080"
    depends_on:
      - user-db
      - kafka
      - redis-users
    env_file:
      - .env
    networks:
      - app-network

  user-db:
    image: postgres:17-alpine
    container_name: userDB
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_DB}
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis-users:
    image: redis:7-alpine
    restart: always
    container_name: redis-users
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_USERS_PASSWORD}
    volumes:
      - redis_users_data:/data
    networks:
      - app-network

  food-delivery-platform-restaurant:
    build:
      context: ./foodDeliveryPlatformRestaurant
      dockerfile: Dockerfile
    container_name: restaurant
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://restaurantDB:5432/${RESTAURANT_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://restaurantDB:5432/${RESTAURANT_DB}
      - SPRING_LIQUIBASE_USER=${POSTGRES_USERNAME}
      - SPRING_LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://localhost,http://localhost:5173,http://frontend:5173
      - ALLOWED_HEADERS=*
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    expose:
      - '8080'
    ports:
      - "8082:8080"
    depends_on:
      - restaurant-db
      - minio
      - redis-restaurants
    env_file:
      - .env
    networks:
      - app-network

  restaurant-db:
    image: postgres:17-alpine
    container_name: restaurantDB
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${RESTAURANT_DB}
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis-restaurants:
    image: redis:7-alpine
    restart: always
    container_name: redis-restaurants
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_RESTAURANTS_PASSWORD}
    volumes:
      - redis_restaurants_data:/data
    networks:
      - app-network

  food-delivery-platform-order:
    build:
      context: ./foodDeliveryPlatformOrder
      dockerfile: Dockerfile
    container_name: order
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orderDB:5432/${ORDER_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://orderDB:5432/${ORDER_DB}
      - SPRING_LIQUIBASE_USER=${POSTGRES_USERNAME}
      - SPRING_LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ALLOWED_ORIGINS=http://localhost,http://localhost:5173,http://frontend:5173
      - ALLOWED_HEADERS=*
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
    expose:
      - '8080'
    ports:
      - "8083:8080"
    depends_on:
      - order-db
      - kafka
      - redis-orders
    env_file:
      - .env
    networks:
      - app-network

  order-db:
    image: postgres:17-alpine
    container_name: orderDB
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDER_DB}
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis-orders:
    image: redis:7-alpine
    restart: always
    container_name: redis-orders
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_ORDERS_PASSWORD}
    volumes:
      - redis_orders_data:/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9090:9090'
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /minio --console-address :9090
    volumes:
      - minio-data:/minio
      - ./foodDeliveryPlatformRestaurant/images/restaurants:/images/restaurants:ro
      - ./foodDeliveryPlatformRestaurant/images/dishes:/images/dishes:ro
      - ./scripts/docker-entrypoint-minio.sh:/docker-entrypoint.sh
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network